spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/sql_stu?serverTimezone=GMT%2b8
#    username: root
#    password: zst0213@
    # 德鲁伊配置开始
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.65:53306/zst?serverTimezone=GMT%2b8
      username: root
      password: zst0213@
      # 配置监控统计拦截的filters，表示可以使用监控过滤器，去掉后监控界面将无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      # 最大活跃数
      max-active: 20
      # 初始化数量
      initial-size: 1
      # 最大连接等待超时时间
      max-wait: 60000
      # 打开PSCache，并且制定每个PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 通过connectionProperties 属性打开mergeSql功能；慢sql记录
      connection-properties: druid.stat.mergeSql=true;durid.stat.slowSqlMillis=5000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 德鲁伊配置结束
  jpa:
    database: mysql
    # 显示sql
    show-sql: false
    # 解决 WARN: spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed
    open-in-view: false
    hibernate:
      # 开启驼峰的配置
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        # 开启sql格式化
        #format_sql: true
        # 指出是什么操作生成了该语句
        #use_sql_comments: true
  redis:
    host: 192.168.2.65
    password: zst0213@
    lettuce:
      pool:
        #连接池最大连接数，使用负数表示没有限制，默认为8
        max-active: 8
        #连接池最大阻塞等待时间，使用负数表示没有限制，默认为-1
        max-wait: -1
        #连接池最大空闲链接数，默认为8
        max-idle: 8
        #连接池最小空闲链接数，默认为0
        min-idle: 0
  elasticsearch:
    rest:
      uris: ["192.168.2.65:9200"]
      username: elastic
      password: zst0213@
# 日志级别，如果与日志配置文件冲突，以日志配置文件为准
logging:
  level:
    org:
      springframework:
        boot:
          # CONDITIONS EVALUATION REPORT 日志不打印
          autoconfigure:
            logging: info
